name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build: &common
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

  test:
    <<: *common

    steps:
      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

  lint:
    <<: *common

    steps:
      - name: Install ESLint
        run: npm install eslint --global

      - name: Lint JavaScript files
        run: eslint .

  deploy:
    needs: [test, lint]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        with:
          args: deploy --prod --dir .
